[OpenCL] Address coverity issue with dodgy struct-to-array casts
oneapi-src/unified-runtime pull request #1054
Opened 2023-11-09 14:59 UTC by aarongreig

Also fix a similar issue coverity had with CreateProgramWithBinary which was passing array pointers straight through to the cl entry point by putting these params in local const arrays.

2023-11-09 17:59 UTC, fabiomestre approved these changes
LGTM

2023-11-10 14:33 UTC, kbenzie requested changes
`urEnqueueMemImageRead` also contains casts from `ur_rect_office_t`/`ur_rect_region_t`, we should fix those here also.

2023-11-10 15:44 UTC, kbenzie approved these changes

2023-11-10 15:49 UTC, kbenzie commented
Seems `source/adapters/opencl/enqueue.cpp` has a conflict now.

2023-11-10 15:55 UTC, kbenzie commented
This also needs an https://github.com/intel/llvm PR.

2023-12-04 12:37 UTC, kbenzie commented
Superceed by #1048

2023-12-04 12:37 UTC, closed without merging