[NATIVECPU] Empty implementation for command buffer fill
oneapi-src/unified-runtime pull request #1247
Opened 2024-01-12 14:25 UTC by PietroGhg

Adds empty implementations for `urCommandBufferAppendMemBufferFillExp` and `urCommandBufferAppendUSMFillExp` on Native CPU.

2024-01-12 14:45 UTC, EwanC commented
There's another couple of command-buffer entry-points added recently that we missed from native-cpu https://github.com/oneapi-src/unified-runtime/pull/937/

* `urCommandBufferAppendUSMPrefetchExp`
* `urCommandBufferAppendUSMAdviseExp`.

Not sure if you want to include those here or a new PR.

2024-01-12 14:54 UTC, martygrant requested changes
Hey Pietro would you mind removing the `die` calls and just leave these entry points as `return UR_RESULT_ERROR_UNSUPPORTED_FEATURE`? We're removing die/abort (https://github.com/oneapi-src/unified-runtime/pull/1127) and handling it in DPC++ (https://github.com/intel/llvm/pull/12361/). Cheers!

2024-01-12 14:58 UTC, PietroGhg commented
> There's another couple of command-buffer entry-points added recently that we missed from native-cpu #937
> 
>     * `urCommandBufferAppendUSMPrefetchExp`
> 
>     * `urCommandBufferAppendUSMAdviseExp`.
> 
> 
> Not sure if you want to include those here or a new PR (happy for you to include them here)

Thanks for pointing it out, I'll include them here

2024-01-12 14:58 UTC, PietroGhg commented
> Hey Pietro would you mind removing the `die` calls and just leave these entry points as `return UR_RESULT_ERROR_UNSUPPORTED_FEATURE`? We're removing die/abort (#1127) and handling it in DPC++ ([intel/llvm#12361](https://github.com/intel/llvm/pull/12361)). Cheers!

Will do, thanks :)

2024-01-12 16:13 UTC, martygrant approved these changes

2024-01-15 08:57 UTC, EwanC approved these changes

2024-01-24 14:27 UTC, merged