[CUDA] Use camelCase always (applied to usm_p2p.cpp).
oneapi-src/unified-runtime pull request #1311
Opened 2024-02-02 12:50 UTC by JackAKirk

Use camelCase naming convention.

This makes the naming convention consistent with the switch to camelCase in other files.

2024-02-02 14:16 UTC, ldrumm requested changes
This is two separate patches.

The first one is NFC and changes only the variable names
The second changes control flow.

The second could be the source of subtle bugs, and doesn't belong with such a commit message

2024-02-02 16:32 UTC, JackAKirk commented
> This is two separate patches.
> 
> The first one is NFC and changes only the variable names The second changes control flow.
> 
> The second could be the source of subtle bugs, and doesn't belong with such a commit message

Thanks, I've removed that part and added it here: https://github.com/oneapi-src/unified-runtime/pull/1317

2024-02-06 11:33 UTC, mmoadeli approved these changes

2024-02-06 14:31 UTC, ldrumm approved these changes

2024-02-06 14:38 UTC, merged