[HIP][CMDBUF] Require ROCm 5.5.1 for HIP command-buffers
oneapi-src/unified-runtime pull request #1447
Opened 2024-03-15 10:48 UTC by EwanC

An issue using the command-buffer experimental feature was discovered using HIP version 5.4.3 - https://github.com/ROCm/HIP/issues/2450

Set the minimum supported version as ROCm 5.5.1 to avoid this bug, as this is the next ROCm available version after 5.4.3 we have have available for testing and can confirm passes the SYCL-Graph tests.

Note: The ROCm version tested by DPC++ GitHub CI is currently 6.0.0.

2024-03-18 18:07 UTC, Bensuo approved these changes

2024-03-18 18:09 UTC, JackAKirk requested changes

2024-03-19 10:37 UTC, EwanC commented on source/adapters/hip/device.cpp
> +    detail::ur::assertion(hipDriverGetVersion(&DriverVersion) == hipSuccess);
Thanks, I missed that PR. Updated to use `UR_CHECK_ERROR` instead now.

2024-03-19 10:40 UTC, JackAKirk approved these changes

2024-03-20 17:15 UTC, merged