[Loader] Supress system errors when loading adapters on Windows
oneapi-src/unified-runtime pull request #2060
Opened 2024-09-05 16:46 UTC by martygrant

@aarongreig 

Disables system errors when loading adapters on Windows, and re-enables them after.

2024-09-09 11:08 UTC, pbalcer approved these changes

2024-09-11 10:35 UTC, aarongreig requested changes

2024-09-11 10:35 UTC, aarongreig commented on source/loader/ur_loader.cpp
> +    // This is crucial for graceful handling of plugins that couldn't be
```suggestion
    // This is crucial for graceful handling of adapters that couldn't be
```

2024-09-11 10:35 UTC, aarongreig commented on source/loader/ur_loader.cpp
> +    // TODO: add reporting in case of an error.
```suggestion
    // loaded, e.g. due to missing native run-times.
    // TODO: add reporting in case of an error.
```

2024-09-12 09:06 UTC, aarongreig approved these changes

2024-09-16 09:20 UTC, merged